services:
  - type: web
    name: 72-dxcluster
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PORT
        value: 8080
    ports:
      - port: 8080
        type: http
      - port: 7300
        type: tcp
